"""v1

Revision ID: 1e2e743784c9
Revises: ccc49321b3ee
Create Date: 2024-06-09 09:31:07.373407

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1e2e743784c9"
down_revision: str | None = "ccc49321b3ee"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "managers",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_managers")),
        sa.UniqueConstraint("telegram_id", name=op.f("uq_managers_telegram_id")),
    )
    op.create_table(
        "bots",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("manager_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["manager_id"],
            ["managers.id"],
            name=op.f("fk_bots_manager_id_managers"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bots")),
        sa.UniqueConstraint("telegram_id", name=op.f("uq_bots_telegram_id")),
        sa.UniqueConstraint("token", name=op.f("uq_bots_token")),
    )
    op.create_table(
        "cities",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("timezone", sa.String(), nullable=False),
        sa.Column("bot_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["bot_id"], ["bots.id"], name=op.f("fk_cities_bot_id_bots"), ondelete="cascade"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cities")),
    )
    op.create_table(
        "services",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=2048), nullable=True),
        sa.Column("bot_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["bot_id"], ["bots.id"], name=op.f("fk_services_bot_id_bots"), ondelete="cascade"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_services")),
    )
    op.create_table(
        "branches",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("city_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["cities.id"],
            name=op.f("fk_branches_city_id_cities"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_branches")),
    )
    op.create_table(
        "clients",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("bot_id", sa.BigInteger(), nullable=False),
        sa.Column("city_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["bot_id"], ["bots.id"], name=op.f("fk_clients_bot_id_bots"), ondelete="cascade"),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["cities.id"],
            name=op.f("fk_clients_city_id_cities"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clients")),
    )
    op.create_table(
        "masters",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("bot_id", sa.BigInteger(), nullable=False),
        sa.Column("city_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["bot_id"], ["bots.id"], name=op.f("fk_masters_bot_id_bots"), ondelete="cascade"),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["cities.id"],
            name=op.f("fk_masters_city_id_cities"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_masters")),
    )
    op.create_table(
        "appointments",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("master_id", sa.BigInteger(), nullable=False),
        sa.Column("client_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_appointments_client_id_clients"),
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["master_id"],
            ["masters.id"],
            name=op.f("fk_appointments_master_id_masters"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_appointments")),
    )
    op.create_table(
        "branch_master_association",
        sa.Column("branch_id", sa.BigInteger(), nullable=False),
        sa.Column("master_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
            name=op.f("fk_branch_master_association_branch_id_branches"),
        ),
        sa.ForeignKeyConstraint(
            ["master_id"],
            ["masters.id"],
            name=op.f("fk_branch_master_association_master_id_masters"),
        ),
        sa.PrimaryKeyConstraint("branch_id", "master_id", name=op.f("pk_branch_master_association")),
    )
    op.create_table(
        "service_master_association",
        sa.Column("work_time", sa.Integer(), nullable=False),
        sa.Column("break_time", sa.Integer(), nullable=False),
        sa.Column("service_id", sa.BigInteger(), nullable=False),
        sa.Column("master_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["master_id"],
            ["masters.id"],
            name=op.f("fk_service_master_association_master_id_masters"),
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
            name=op.f("fk_service_master_association_service_id_services"),
        ),
        sa.PrimaryKeyConstraint("service_id", "master_id", name=op.f("pk_service_master_association")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("service_master_association")
    op.drop_table("branch_master_association")
    op.drop_table("appointments")
    op.drop_table("masters")
    op.drop_table("clients")
    op.drop_table("branches")
    op.drop_table("services")
    op.drop_table("cities")
    op.drop_table("bots")
    op.drop_table("managers")
    op.execute("DROP TYPE locale;")
    # ### end Alembic commands ###
